name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: 'javascript'

      - name: Nrwl Nx
        uses: MansaGroup/nrwl-nx-action@v2.0.4
        with:
          targets: lint,test,build
          args: --codeCoverage

      - name: Codecov
        uses: codecov/codecov-action@v1.5.2
        with:
          # Repository upload token - get it from codecov.io. Required only for private repositories
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: /coverage
          name: Rat.App Code Coverage
          verbose: true


      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1


  docker:
    needs: build
    runs-on: ubuntu-latest
    env:
      TYPE: 'all' # 'all', 'docker', 'github'

    steps:
      - name: Print info
        run: |
          echo ${{ env.TYPE }}
