name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: 'javascript'

      - name: Setup Node.js
        uses: actions/setup-node@v2.2.0
        with:
          # Used to specify a package manager for caching in the default directory. Supported values: npm, yarn
          cache: npm

      - name: NPM install
        run: npm ci

      - name: NX Lint
        uses: MansaGroup/nrwl-nx-action@v2.0.4
        with:
          targets: lint

      - name: NX Test
        uses: MansaGroup/nrwl-nx-action@v2.0.4
        with:
          targets: test
          affected: false
          args: --code-coverage

      - name: NX Build
        uses: MansaGroup/nrwl-nx-action@v2.0.4
        with:
          targets: build

      - name: Code Coverage - Client
        uses: codecov/codecov-action@v1.5.2
        with:
          files: ./coverage/*/lcov.info
          name: Rat.App Code Coverage


      - name: CodeQL Analysis
        uses: github/codeql-action/analyze@v1


  docker:
    needs: build
    runs-on: ubuntu-latest
    env:
      TYPE: 'all' # 'all', 'docker', 'github'

    steps:
      - name: Print info
        run: |
          echo ${{ env.TYPE }}
